- name: Install loadbalancer
  become: true
  hosts: loadbalancer
  tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: true
    
    - name: install packages
      ansible.builtin.apt:
        name: nginx
        
    - name: copy nginx.conf for loadbalancer
      ansible.builtin.template:
        src: ./data/load_balancer.j2
        dest: /etc/nginx/nginx.conf

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
    

