- name: Install NGINX
  become: yes
  hosts: webservers
  environment:
    LUAJIT_LIB: /usr/local/lib/
    LUAJIT_INC: /usr/local/include/luajit-2.1/
  
  tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: true

    - name: install packages
      ansible.builtin.apt:
        name: 
          - build-essential 
          - libpcre3
          - libpcre3-dev
          - libcurl4-openssl-dev
          - libssl-dev
          - zlib1g
          - zlib1g-dev
          - gcc
          - wget
          - curl
          - make
          - perl
        state: present
    

    - name: make source directory
      ansible.builtin.file:
        path: /tmp/source
        state: directory
    
    - name: make data directory for nginx
      ansible.builtin.file:
        path: /data/sites
        state: directory

    - name: run wget for all parts to my NGINX
      ansible.builtin.uri: 
        url: "{{ item.url }}"
        dest: /tmp/source/
      with_items:
        - url: https://nginx.org/download/nginx-1.24.0.tar.gz
        - url: https://github.com/openresty/luajit2/archive/refs/tags/v2.1-20230410.tar.gz
        - url: https://github.com/vision5/ngx_devel_kit/archive/refs/tags/v0.3.2.tar.gz
        - url: https://github.com/openresty/lua-nginx-module/archive/refs/tags/v0.10.24.tar.gz
        - url: https://github.com/openresty/lua-resty-core/archive/refs/tags/v0.1.26.tar.gz
        - url: https://github.com/openresty/lua-resty-lrucache/archive/refs/tags/v0.13.tar.gz

    - name: run tar command
      ansible.builtin.command:
          cmd: tar -xzvf "{{item}}"
          chdir: /tmp/source
      with_items:
        - "nginx-1.24.0.tar.gz"
        - "luajit2-2.1-20230410.tar.gz"
        - "ngx_devel_kit-0.3.2.tar.gz"
        - "lua-nginx-module-0.10.24.tar.gz"
        - "lua-resty-core-0.1.26.tar.gz"
        - "lua-resty-lrucache-0.13.tar.gz"

    - name: make install LUAJIT
      ansible.builtin.command:
        cmd: "{{item}}"
        chdir: /tmp/source/luajit2-2.1-20230410
      with_items:
        - make
        - make install

    - name: copy configure.sh files
      ansible.builtin.copy:
        src: ./data/configure.sh
        dest: /tmp/source/nginx-1.24.0/configure.sh
        mode: '777'

    - name: Configure NGINX
      ansible.builtin.shell:
        cmd: ./configure.sh
        chdir: /tmp/source/nginx-1.24.0/

    - name: make install NGINX
      ansible.builtin.command:
        cmd: "{{item}}"
        chdir: /tmp/source/nginx-1.24.0/
      with_items:
        - make
        - make install

    - name: make install LUA - resty core
      ansible.builtin.command:
        cmd: "{{item}}"
        chdir: /tmp/source/lua-resty-core-0.1.26/
      with_items:
        - make
        - make install PREFIX=/usr/local/nginx

    - name: make install LUA - resty luacache
      ansible.builtin.command:
        cmd: "{{item}}"
        chdir: /tmp/source/lua-resty-lrucache-0.13/
      with_items:
        - make
        - make install PREFIX=/usr/local/nginx

    - name: generate config file
      ansible.builtin.template:
        src: ./data/nginx.j2
        dest: /etc/nginx/nginx.conf
    
    - name: copy nginx service file
      ansible.builtin.copy:
        src: ./data/nginx.service
        dest: /lib/systemd/system/nginx.service

    - name: generate HTML site files
      ansible.builtin.template:
        src: ./data/sites/index.j2
        dest: /data/sites/
    
    - name: generate LUA site files
      ansible.builtin.template:
        src: ./data/sites/page.j2
        dest: /data/sites/page.lua
      notify: 
        - start nginx

handlers:
  - name: start NGINX
    ansible.builtin.shell:
      cmd: systemctl start nginx